version: '3.7'

services:
  maven:
    container_name: maven
    image: maven:3.6.1-jdk-8-alpine
    volumes:
    - ./:/ws
    - $HOME/.m2:/root/.m2
    working_dir: /ws
    entrypoint: /bin/sh -c 'apk update && apk add tree inotify-tools && tail -f'
